version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-and-test-user-microservices:
    working_directory: ~/nest-microservices/user-svc
    docker:
      - image: cimg/node:14.15
      - image: circleci/redis
        environment:
          REDIS_URL: redis://localhost:6379
    executor: node/default
    steps:
      - checkout:
          path: ~/nest-microservices
      - node/install-packages:
          app-dir: ~/nest-microservices/user-svc
          pkg-manager: yarn
          with-cache: true
          cache-path: ~/.yarn
          cache-version: v1
          include-branch-in-cache-key: true
      - run:
          name: Check Node Version
          description: Check node version that have been installed on the docker image
          command: node --version
      - run:
          name: Check Yarn Version
          description: Check yarn version that have been installed on the docker image
          command: yarn --version
      - run:
          name: Unit Testing
          description: Start the unit testing on user services
          command: yarn test
      - run:
          name: End to End Testing
          description: Start the end to end testing for user microservices
          command: yarn test:e2e
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  build-and-test-user-microservices:
    jobs:
      - build-and-test-user-microservices
